export const LOAD_CONTACTS_ACTION = 'LOAD_CONTACTS';
export const LOAD_CONTACTS_SUCCESS_ACTION = 'LOAD_CONTACTS_SUCCESS';
export const LOAD_CONTACTS_FAILED_ACTION = 'LOAD_CONTACTS_FAILED';

export const ADD_NEW_CONTACT_ACTION = 'ADD_NEW_CONTACT';
