export const LOAD_CONTACTS_ACTION = 'LOAD_CONTACTS';
export const LOAD_CONTACTS_SUCCESS_ACTION = 'LOAD_CONTACTS_SUCCESS';
export const LOAD_CONTACTS_FAILED_ACTION = 'LOAD_CONTACTS_FAILED';

export const ADD_NEW_CONTACT_ACTION = 'ADD_NEW_CONTACT';
export const UPDATE_CONTACT_ACTION = 'UPDATE_CONTACT';
export const SEARCH_CONTACTS_ACTION = 'SEARCH_CONTACTS';
export const EDIT_CONTACT_ACTION = 'EDIT_CONTACT';
export const RESET_EDIT_CONTACT_ACTION = 'RESET_EDIT_CONTACT';

export const ADD_NEW_CONTACT_USER_INPUT_ACTION = 'ADD_NEW_CONTACT_USER_INPUT';